package com.sg.sgrr.Retrofit

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

data class games(
        @SerializedName("code") @Expose val code: Int,
        @SerializedName("message") @Expose val message: String,
        @SerializedName("userGames") @Expose val userGames: List<userGames>
)
data class userGames(
        @SerializedName("userNum") @Expose val userNum: Int,
        @SerializedName("nickname") @Expose val nickname: String,
        @SerializedName("gameId") @Expose val gameId: Int,
        @SerializedName("seasonId") @Expose val seasonId: Int,
        @SerializedName("matchingMode") @Expose val matchingMode: Int,
        @SerializedName("matchingTeamMode") @Expose val matchingTeamMode: Int,
        @SerializedName("characterNum") @Expose val characterNum: Int,
        @SerializedName("skinCode") @Expose val skinCode: Int,
        @SerializedName("characterLevel") @Expose val characterLevel: Int,
        @SerializedName("gameRank") @Expose val gameRank: Int,
        @SerializedName("playerKill") @Expose val playerKill: Int,
        @SerializedName("playerAssistant") @Expose val playerAssistant: Int,
        @SerializedName("monsterKill") @Expose val monsterKill: Int,
        @SerializedName("bestWeapon") @Expose val bestWeapon: Int,
        @SerializedName("bestWeaponLevel") @Expose val bestWeaponLevel: Int,
        @SerializedName("masteryLevel") @Expose val masteryLevel: Map<String, Int>,
        @SerializedName("equipment") @Expose val equipment: Map<String, Int>,
        @SerializedName("versionMajor") @Expose val versionMajor: Int,
        @SerializedName("versionMinor") @Expose val versionMinor: Int,
        @SerializedName("skillLevelInfo") @Expose val skillLevelInfo: Map<String, Int>,
        @SerializedName("skillOrderInfo") @Expose val skillOrderInfo: Map<String, Int>,
        @SerializedName("serverName") @Expose val serverName: String,
        @SerializedName("maxHp") @Expose val maxHp: Int,
        @SerializedName("maxSp") @Expose val maxSp: Int,
        @SerializedName("attackPower") @Expose val attackPower: Int,
        @SerializedName("defense") @Expose val defense: Double,
        @SerializedName("hpRegen") @Expose val hpRegen: Double,
        @SerializedName("spRegen") @Expose val spRegen: Double,
        @SerializedName("attackSpeed") @Expose val attackSpeed: Double,
        @SerializedName("moveSpeed") @Expose val moveSpeed: Double,
        @SerializedName("outOfCombatMoveSpeed") @Expose val outOfCombatMoveSpeed: Double,
        @SerializedName("sightRange") @Expose val sightRange: Double,
        @SerializedName("attackRange") @Expose val attackRange: Double,
        @SerializedName("criticalStrikeChance") @Expose val criticalStrikeChance: Double,
        @SerializedName("criticalStrikeDamage") @Expose val criticalStrikeDamage: Double,
        @SerializedName("coolDownReduction") @Expose val coolDownReduction: Double,
        @SerializedName("lifeSteal") @Expose val lifeSteal: Double,
        @SerializedName("amplifierToMonster") @Expose val amplifierToMonster: Double,
        @SerializedName("trapDamage") @Expose val trapDamage: Double,
        @SerializedName("gainExp") @Expose val gainExp: Int,
        @SerializedName("startDtm") @Expose val startDtm: String,
        @SerializedName("duration") @Expose val duration: Int,
        @SerializedName("mmrBefore") @Expose val mmrBefore: Int,
        @SerializedName("damageToPlayer") @Expose val damageToPlayer: Int,
        @SerializedName("damageToMonster") @Expose val damageToMonster: Int,
        @SerializedName("killerUserNum") @Expose val killerUserNum: Int,
        @SerializedName("playTime") @Expose val playTime: Int,
        @SerializedName("watchTime") @Expose val watchTime: Int,
        @SerializedName("totalTime") @Expose val totalTime: Int,
        @SerializedName("botAdded") @Expose val botAdded: Int,
        @SerializedName("botRemain") @Expose val botRemain: Int,
        @SerializedName("restrictedAreaAccelerated") @Expose val restrictedAreaAccelerated: Int,
        @SerializedName("safeAreas") @Expose val safeAreas: Int,
        @SerializedName("killer") @Expose val killer: String,
        @SerializedName("killDetail") @Expose val killDetail: String,
        @SerializedName("causeOfDeath") @Expose val causeOfDeath: String,
        @SerializedName("teamNumber") @Expose val teamNumber: Int,
        @SerializedName("preMade") @Expose val preMade: Int,
        @SerializedName("gainedNormalMmrKFactor") @Expose val gainedNormalMmrKFactor: Double,
        @SerializedName("victory") @Expose val victory: Int,
        @SerializedName("craftUncommon") @Expose val craftUncommon: Int,
        @SerializedName("craftRare") @Expose val craftRare: Int,
        @SerializedName("craftEpic") @Expose val craftEpic: Int,
        @SerializedName("craftLegend") @Expose val craftLegend: Int,
        @SerializedName("trapDamageToPlayer") @Expose val trapDamageToPlayer: Int,
        @SerializedName("basicAttackDamageToPlayer") @Expose val basicAttackDamageToPlayer: Int,
        @SerializedName("skillDamageToPlayer") @Expose val skillDamageToPlayer: Int,
)