package com.sg.sgrr

data class Weapon(
    val code: Int,
    val name: String,
    val itemType: String,
    val weaponType: String,
    val itemGrade: String,
    val craftAnimTrigger: String,
    val stackable: Int,
    val initialCount: Int,
    val makeMaterial1: Int,
    val makeMaterial2: Int,
    val consumable: Boolean,
    val attackPower: Int,
    val defense: Int,
    val maxHp: Int,
    val hpRegenRatio: Int,
    val hpRegen: Int,
    val spRegenRatio: Int,
    val spRegen: Int,
    val attackSpeedRatio: Int,
    val criticalStrikeChance: Int,
    val criticalStrikeDamage: Int,
    val cooldownReduction: Int,
    val lifeSteal: Int,
    val moveSpeed: Int,
    val sightRange: Int,
    val attackRange: Int,
    val increaseBasicAttackDamage: Int,
    val increaseSkillDamage: Int,
    val increaseSkillDamageRatio: Int,
    val decreaseRecoveryToBasicAttack: Int,
    val decreaseRecoveryToSkill: Int
)